unstable_features = true
hard_tabs = true
overflow_delimited_expr = true
match_block_trailing_comma = true
imports_granularity = "Module"
group_imports = "StdExternalCrate"
use_small_heuristics = "Max"
where_single_line = true